"""core schema

Revision ID: 091d0853d794
Revises: dcd649568149
Create Date: 2026-02-09 22:26:49.272449
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '091d0853d794'
down_revision = 'dcd649568149'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
